export const proficiencies = [
    { key: "12", label: "Expert" },
    { key: "11", label: "Very good" },
    { key: "9", label: "Good" },
    { key: "7", label: "Competent" },
    { key: "5", label: "Modest" },
    { key: "4", label: "Limited" },
    { key: "0", label: "None at all" },
];

export const countries = [
    { key: "Canada", label: "Canada" },
    { key: "Afghanistan", label: "Afghanistan" },
    { key: "Albania", label: "Albania" },
    { key: "Algeria", label: "Algeria" },
    { key: "American Samoa", label: "American Samoa" },
    { key: "Andorra", label: "Andorra" },
    { key: "Angola", label: "Angola" },
    { key: "Anguilla", label: "Anguilla" },
    { key: "Antarctica", label: "Antarctica" },
    { key: "Antigua and Barbuda", label: "Antigua and Barbuda" },
    { key: "Argentina", label: "Argentina" },
    { key: "Armenia", label: "Armenia" },
    { key: "Aruba", label: "Aruba" },
    { key: "Australia", label: "Australia" },
    { key: "Austria", label: "Austria" },
    { key: "Azerbaijan", label: "Azerbaijan" },
    { key: "Bahamas", label: "Bahamas" },
    { key: "Bahrain", label: "Bahrain" },
    { key: "Bangladesh", label: "Bangladesh" },
    { key: "Barbados", label: "Barbados" },
    { key: "Belarus", label: "Belarus" },
    { key: "Belgium", label: "Belgium" },
    { key: "Belize", label: "Belize" },
    { key: "Benin", label: "Benin" },
    { key: "Bermuda", label: "Bermuda" },
    { key: "Bhutan", label: "Bhutan" },
    { key: "Bolivia", label: "Bolivia" },
    { key: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
    { key: "Botswana", label: "Botswana" },
    { key: "Bouvet Island", label: "Bouvet Island" },
    { key: "Brazil", label: "Brazil" },
    { key: "British Indian Ocean Territory",label: "British Indian Ocean Territory", },
    { key: "Brunei Darussalam", label: "Brunei Darussalam" },
    { key: "Bulgaria", label: "Bulgaria" },
    { key: "Burkina Faso", label: "Burkina Faso" },
    { key: "Burundi", label: "Burundi" },
    { key: "Cambodia", label: "Cambodia" },
    { key: "Cameroon", label: "Cameroon" },
    { key: "Cape Verde", label: "Cape Verde" },
    { key: "Caribbean Netherlands ", label: "Caribbean Netherlands " },
    { key: "Cayman Islands", label: "Cayman Islands" },
    { key: "Central African Republic", label: "Central African Republic" },
    { key: "Chad", label: "Chad" },
    { key: "Chile", label: "Chile" },
    { key: "China", label: "China" },
    { key: "Christmas Island", label: "Christmas Island" },
    { key: "Cocos (Keeling) Islands", label: "Cocos (Keeling) Islands" },
    { key: "Colombia", label: "Colombia" },
    { key: "Comoros", label: "Comoros" },
    { key: "Congo", label: "Congo" },
    {
      key: "Congo, Democratic Republic of",
      label: "Congo, Democratic Republic of",
    },
    { key: "Cook Islands", label: "Cook Islands" },
    { key: "Costa Rica", label: "Costa Rica" },
    { key: "Croatia", label: "Croatia" },
    { key: "Cuba", label: "Cuba" },
    { key: "Curaçao", label: "Curaçao" },
    { key: "Cyprus", label: "Cyprus" },
    { key: "Czech Republic", label: "Czech Republic" },
    { key: "Côte d'Ivoire", label: "Côte d'Ivoire" },
    { key: "Denmark", label: "Denmark" },
    { key: "Djibouti", label: "Djibouti" },
    { key: "Dominica", label: "Dominica" },
    { key: "Dominican Republic", label: "Dominican Republic" },
    { key: "Ecuador", label: "Ecuador" },
    { key: "Egypt", label: "Egypt" },
    { key: "El Salvador", label: "El Salvador" },
    { key: "Equatorial Guinea", label: "Equatorial Guinea" },
    { key: "Eritrea", label: "Eritrea" },
    { key: "Estonia", label: "Estonia" },
    { key: "Ethiopia", label: "Ethiopia" },
    { key: "Falkland Islands", label: "Falkland Islands" },
    { key: "Faroe Islands", label: "Faroe Islands" },
    { key: "Fiji", label: "Fiji" },
    { key: "Finland", label: "Finland" },
    { key: "France", label: "France" },
    { key: "French Guiana", label: "French Guiana" },
    { key: "French Polynesia", label: "French Polynesia" },
    {
      key: "French Southern Territories",
      label: "French Southern Territories",
    },
    { key: "Gabon", label: "Gabon" },
    { key: "Gambia", label: "Gambia" },
    { key: "Georgia", label: "Georgia" },
    { key: "Germany", label: "Germany" },
    { key: "Ghana", label: "Ghana" },
    { key: "Gibraltar", label: "Gibraltar" },
    { key: "Greece", label: "Greece" },
    { key: "Greenland", label: "Greenland" },
    { key: "Grenada", label: "Grenada" },
    { key: "Guadeloupe", label: "Guadeloupe" },
    { key: "Guam", label: "Guam" },
    { key: "Guatemala", label: "Guatemala" },
    { key: "Guernsey", label: "Guernsey" },
    { key: "Guinea", label: "Guinea" },
    { key: "Guinea-Bissau", label: "Guinea-Bissau" },
    { key: "Guyana", label: "Guyana" },
    { key: "Haiti", label: "Haiti" },
    {
      key: "Heard and McDonald Islands",
      label: "Heard and McDonald Islands",
    },
    { key: "Honduras", label: "Honduras" },
    { key: "Hong Kong", label: "Hong Kong" },
    { key: "Hungary", label: "Hungary" },
    { key: "Iceland", label: "Iceland" },
    { key: "India", label: "India" },
    { key: "Indonesia", label: "Indonesia" },
    { key: "Iran", label: "Iran" },
    { key: "Iraq", label: "Iraq" },
    { key: "Ireland", label: "Ireland" },
    { key: "Isle of Man", label: "Isle of Man" },
    { key: "Israel", label: "Israel" },
    { key: "Italy", label: "Italy" },
    { key: "Jamaica", label: "Jamaica" },
    { key: "Japan", label: "Japan" },
    { key: "Jersey", label: "Jersey" },
    { key: "Jordan", label: "Jordan" },
    { key: "Kazakhstan", label: "Kazakhstan" },
    { key: "Kenya", label: "Kenya" },
    { key: "Kiribati", label: "Kiribati" },
    { key: "Kozovo", label: "Kozovo" },
    { key: "Kuwait", label: "Kuwait" },
    { key: "Kyrgyzstan", label: "Kyrgyzstan" },
    {
      key: "Lao People's Democratic Republic",
      label: "Lao People's Democratic Republic",
    },
    { key: "Latvia", label: "Latvia" },
    { key: "Lebanon", label: "Lebanon" },
    { key: "Lesotho", label: "Lesotho" },
    { key: "Liberia", label: "Liberia" },
    { key: "Libya", label: "Libya" },
    { key: "Liechtenstein", label: "Liechtenstein" },
    { key: "Lithuania", label: "Lithuania" },
    { key: "Luxembourg", label: "Luxembourg" },
    { key: "Macau", label: "Macau" },
    { key: "Macedonia", label: "Macedonia" },
    { key: "Madagascar", label: "Madagascar" },
    { key: "Malawi", label: "Malawi" },
    { key: "Malaysia", label: "Malaysia" },
    { key: "Maldives", label: "Maldives" },
    { key: "Mali", label: "Mali" },
    { key: "Malta", label: "Malta" },
    { key: "Marshall Islands", label: "Marshall Islands" },
    { key: "Martinique", label: "Martinique" },
    { key: "Mauritania", label: "Mauritania" },
    { key: "Mauritius", label: "Mauritius" },
    { key: "Mayotte", label: "Mayotte" },
    { key: "Mexico", label: "Mexico" },
    {
      key: "Micronesia, Federated States of",
      label: "Micronesia, Federated States of",
    },
    { key: "Moldova", label: "Moldova" },
    { key: "Monaco", label: "Monaco" },
    { key: "Mongolia", label: "Mongolia" },
    { key: "Montenegro", label: "Montenegro" },
    { key: "Montserrat", label: "Montserrat" },
    { key: "Morocco", label: "Morocco" },
    { key: "Mozambique", label: "Mozambique" },
    { key: "Myanmar", label: "Myanmar" },
    { key: "Namibia", label: "Namibia" },
    { key: "Nauru", label: "Nauru" },
    { key: "Nepal", label: "Nepal" },
    { key: "New Caledonia", label: "New Caledonia" },
    { key: "New Zealand", label: "New Zealand" },
    { key: "Nicaragua", label: "Nicaragua" },
    { key: "Niger", label: "Niger" },
    { key: "Nigeria", label: "Nigeria" },
    { key: "Niue", label: "Niue" },
    { key: "Norfolk Island", label: "Norfolk Island" },
    { key: "North Korea", label: "North Korea" },
    { key: "Northern Mariana Islands", label: "Northern Mariana Islands" },
    { key: "Norway", label: "Norway" },
    { key: "Oman", label: "Oman" },
    { key: "Pakistan", label: "Pakistan" },
    { key: "Palau", label: "Palau" },
    { key: "Palestine, State of", label: "Palestine, State of" },
    { key: "Panama", label: "Panama" },
    { key: "Papua New Guinea", label: "Papua New Guinea" },
    { key: "Paraguay", label: "Paraguay" },
    { key: "Peru", label: "Peru" },
    { key: "Philippines", label: "Philippines" },
    { key: "Pitcairn", label: "Pitcairn" },
    { key: "Poland", label: "Poland" },
    { key: "Portugal", label: "Portugal" },
    { key: "Puerto Rico", label: "Puerto Rico" },
    { key: "Qatar", label: "Qatar" },
    { key: "Romania", label: "Romania" },
    { key: "Russian Federation", label: "Russian Federation" },
    { key: "Rwanda", label: "Rwanda" },
    { key: "Réunion", label: "Réunion" },
    { key: "Saint Barthélemy", label: "Saint Barthélemy" },
    { key: "Saint Helena", label: "Saint Helena" },
    { key: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
    { key: "Saint Lucia", label: "Saint Lucia" },
    {
      key: "Saint Vincent and the Grenadines",
      label: "Saint Vincent and the Grenadines",
    },
    { key: "Saint-Martin (France)", label: "Saint-Martin (France)" },
    { key: "Samoa", label: "Samoa" },
    { key: "San Marino", label: "San Marino" },
    { key: "Sao Tome and Principe", label: "Sao Tome and Principe" },
    { key: "Saudi Arabia", label: "Saudi Arabia" },
    { key: "Senegal", label: "Senegal" },
    { key: "Serbia", label: "Serbia" },
    { key: "Seychelles", label: "Seychelles" },
    { key: "Sierra Leone", label: "Sierra Leone" },
    { key: "Singapore", label: "Singapore" },
    { key: "Sint Maarten (Dutch part)", label: "Sint Maarten (Dutch part)" },
    { key: "Slovakia", label: "Slovakia" },
    { key: "Slovenia", label: "Slovenia" },
    { key: "Solomon Islands", label: "Solomon Islands" },
    { key: "Somalia", label: "Somalia" },
    { key: "South Africa", label: "South Africa" },
    {
      key: "South Georgia and the South Sandwich Islands",
      label: "South Georgia and the South Sandwich Islands",
    },
    { key: "South Korea", label: "South Korea" },
    { key: "South Sudan", label: "South Sudan" },
    { key: "Spain", label: "Spain" },
    { key: "Sri Lanka", label: "Sri Lanka" },
    { key: "St. Pierre and Miquelon", label: "St. Pierre and Miquelon" },
    { key: "Sudan", label: "Sudan" },
    { key: "Suriname", label: "Suriname" },
    {
      key: "Svalbard and Jan Mayen Islands",
      label: "Svalbard and Jan Mayen Islands",
    },
    { key: "Swaziland", label: "Swaziland" },
    { key: "Sweden", label: "Sweden" },
    { key: "Switzerland", label: "Switzerland" },
    { key: "Syria", label: "Syria" },
    { key: "Taiwan", label: "Taiwan" },
    { key: "Tajikistan", label: "Tajikistan" },
    { key: "Tanzania", label: "Tanzania" },
    { key: "Thailand", label: "Thailand" },
    { key: "The Netherlands", label: "The Netherlands" },
    { key: "Timor-Leste", label: "Timor-Leste" },
    { key: "Togo", label: "Togo" },
    { key: "Tokelau", label: "Tokelau" },
    { key: "Tonga", label: "Tonga" },
    { key: "Trinidad and Tobago", label: "Trinidad and Tobago" },
    { key: "Tunisia", label: "Tunisia" },
    { key: "Turkey", label: "Turkey" },
    { key: "Turkmenistan", label: "Turkmenistan" },
    { key: "Turks and Caicos Islands", label: "Turks and Caicos Islands" },
    { key: "Tuvalu", label: "Tuvalu" },
    { key: "Uganda", label: "Uganda" },
    { key: "Ukraine", label: "Ukraine" },
    { key: "United Arab Emirates", label: "United Arab Emirates" },
    { key: "United Kingdom", label: "United Kingdom" },
    { key: "United States", label: "United States" },
    {
      key: "United States Minor Outlying Islands",
      label: "United States Minor Outlying Islands",
    },
    { key: "Uruguay", label: "Uruguay" },
    { key: "Uzbekistan", label: "Uzbekistan" },
    { key: "Vanuatu", label: "Vanuatu" },
    { key: "Vatican", label: "Vatican" },
    { key: "Venezuela", label: "Venezuela" },
    { key: "Vietnam", label: "Vietnam" },
    { key: "Virgin Islands (British)", label: "Virgin Islands (British)" },
    { key: "Virgin Islands (U.S.)", label: "Virgin Islands (U.S.)" },
    { key: "Wallis and Futuna Islands", label: "Wallis and Futuna Islands" },
    { key: "Western Sahara", label: "Western Sahara" },
    { key: "Yemen", label: "Yemen" },
    { key: "Zambia", label: "Zambia" },
    { key: "Zimbabwe", label: "Zimbabwe" },
    { key: "Åland Islands", label: "Åland Islands" },
  ];

export const currencies = [
    { key: "AFN", label: "Afghanistan Afghani (؋)" },
    { key: "ALL", label: "Albania Lek (Lek)" },
    { key: "DZD", label: "Algeria Dinar (DA)" },
    { key: "AOA", label: "Angola Kwanza (Kz)" },
    { key: "ARS", label: "Argentina Peso ($)" },
    { key: "AMD", label: "Armenia Dram (դր.)" },
    { key: "AWG", label: "Aruba Guilder ()" },
    { key: "AUD", label: "Australia Dollar ($)" },
    { key: "AZN", label: "Azerbaijan Manat (ман.)" },
    { key: "BSD", label: "Bahamas Dollar ($)" },
    { key: "BHD", label: "Bahrain Dinar (BD)" },
    { key: "BDT", label: "Bangladesh Taka (৳)" },
    { key: "BBD", label: "Barbados Dollar ($)" },
    { key: "BYR", label: "Belarus Ruble (p.)" },
    { key: "BZD", label: "Belize Dollar (BZ$)" },
    { key: "BMD", label: "Bermuda Dollar ($)" },
    { key: "BTN", label: "Bhutan Ngultrum (Nu.)" },
    { key: "BOB", label: "Bolivia Bolíviano ($b)" },
    { key: "BAM", label: "Bosnia and Herzegovina Convertible Marka (KM)" },
    { key: "BWP", label: "Botswana Pula (P)" },
    { key: "BRL", label: "Brazil Real (R$)" },
    { key: "BND", label: "Brunei Darussalam Dollar (B$)" },
    { key: "BGN", label: "Bulgaria Lev (лв.)" },
    { key: "BIF", label: "Burundi Franc (FBu)" },
    { key: "KHR", label: "Cambodia Riel ()" },
    { key: "CAD", label: "Canada Dollar ($)" },
    { key: "CVE", label: "Cape Verde Escudo (CV$)" },
    { key: "KYD", label: "Cayman Islands Dollar (CI$)" },
    { key: "XAF", label: "Central African CFA Franc BEAC (FCFA)" },
    { key: "CLP", label: "Chile Peso ($)" },
    { key: "CNY", label: "China Yuan Renminbi (CN¥)" },
    { key: "COP", label: "Colombia Peso ($)" },
    {
      key: "XOF",
      label: "Communauté Financière Africaine (BCEAO) Franc (F)",
    },
    { key: "KMF", label: "Comorian Franc (CF)" },
    { key: "XPF", label: "Comptoirs Français du Pacifique (CFP) Franc (F)" },
    { key: "CDF", label: "Congo/Kinshasa Franc (FC)" },
    { key: "CRC", label: "Costa Rica Colon (₡)" },
    { key: "HRK", label: "Croatia Kuna (kn)" },
    { key: "CUP", label: "Cuba Peso ($MN)" },
    { key: "CZK", label: "Czech Republic Koruna (Kč)" },
    { key: "DKK", label: "Denmark Krone (kr.)" },
    { key: "DJF", label: "Djibouti Franc (Fdj)" },
    { key: "DOP", label: "Dominican Republic Peso (RD$)" },
    { key: "XCD", label: "East Caribbean Dollar ($)" },
    { key: "EGP", label: "Egypt Pound (E£)" },
    { key: "SVC", label: "El Salvador Colon (₡)" },
    { key: "ERN", label: "Eritrea Nakfa (Nfk)" },
    { key: "ETB", label: "Ethiopia Birr (Br)" },
    { key: "EUR", label: "Euro Member Countries (€)" },
    { key: "FKP", label: "Falkland Islands (Malvinas) Pound (FK£)" },
    { key: "FJD", label: "Fiji Dollar (FJ$)" },
    { key: "GMD", label: "Gambia Dalasi (D)" },
    { key: "GEL", label: "Georgia Lari (GEL)" },
    { key: "GHS", label: "Ghana Cedi (₵)" },
    { key: "GIP", label: "Gibraltar Pound (£)" },
    { key: "GTQ", label: "Guatemala Quetzal (Q)" },
    { key: "GGP", label: "Guernsey Pound (£)" },
    { key: "GNF", label: "Guinea Franc (FG)" },
    { key: "GYD", label: "Guyana Dollar (GY$)" },
    { key: "HTG", label: "Haiti Gourde (G)" },
    { key: "HNL", label: "Honduras Lempira (L)" },
    { key: "HKD", label: "Hong Kong Dollar (HK$)" },
    { key: "HUF", label: "Hungary Forint (Ft)" },
    { key: "ISK", label: "Iceland Krona (kr)" },
    { key: "INR", label: "India Rupee (টকা)" },
    { key: "IDR", label: "Indonesia Rupiah (Rp)" },
    { key: "IRR", label: "Iran Rial (Rl.)" },
    { key: "IQD", label: "Iraq Dinar (ID)" },
    { key: "IMP", label: "Isle of Man Pound (M£)" },
    { key: "ILS", label: "Israel Shekel ()" },
    { key: "JMD", label: "Jamaica Dollar ($)" },
    { key: "JPY", label: "Japan Yen (¥)" },
    { key: "JEP", label: "Jersey Pound (£)" },
    { key: "JOD", label: "Jordan Dinar (JD)" },
    { key: "KZT", label: "Kazakhstan Tenge (тңг.)" },
    { key: "KES", label: "Kenya Shilling (KSh)" },
    { key: "KPW", label: "Korea (North) Won (₩)" },
    { key: "KRW", label: "Korea (South) Won (₩)" },
    { key: "KWD", label: "Kuwait Dinar (K.D.)" },
    { key: "KGS", label: "Kyrgyzstan Som (K.S.)" },
    { key: "LAK", label: "Laos Kip ()" },
    { key: "LBP", label: "Lebanon Pound (L£)" },
    { key: "LSL", label: "Lesotho Loti (L)" },
    { key: "LRD", label: "Liberia Dollar (L$)" },
    { key: "LYD", label: "Libya Dinar (LD)" },
    { key: "MOP", label: "Macau Pataca (MOP$)" },
    { key: "MKD", label: "Macedonia Denar (ден)" },
    { key: "MGA", label: "Madagascar Ariary (Ar)" },
    { key: "MWK", label: "Malawi Kwacha (MK)" },
    { key: "MYR", label: "Malaysia Ringgit (RM)" },
    { key: "MVR", label: "Maldives (Maldive Islands) Rufiyaa (Rf)" },
    { key: "MRO", label: "Mauritania Ouguiya (UM)" },
    { key: "MUR", label: "Mauritius Rupee (Rs)" },
    { key: "MXN", label: "Mexico Peso (Mex$)" },
    { key: "MDL", label: "Moldova Leu (MDL)" },
    { key: "MNT", label: "Mongolia Tughrik ()" },
    { key: "MAD", label: "Morocco Dirham (Dh)" },
    { key: "MZN", label: "Mozambique Metical (MT)" },
    { key: "MMK", label: "Myanmar (Burma) Kyat (K)" },
    { key: "NAD", label: "Namibia Dollar (N$)" },
    { key: "NPR", label: "Nepal Rupee (Rps)" },
    { key: "ANG", label: "Netherlands Antilles Guilder (NAƒ)" },
    { key: "NZD", label: "New Zealand Dollar ($)" },
    { key: "NIO", label: "Nicaragua Cordoba (C$)" },
    { key: "NGN", label: "Nigeria Naira (₦)" },
    { key: "NOK", label: "Norway Krone (kr)" },
    { key: "OMR", label: "Oman Rial (RO)" },
    { key: "PKR", label: "Pakistan Rupee (Re.)" },
    { key: "PAB", label: "Panama Balboa (B/.)" },
    { key: "PGK", label: "Papua New Guinea Kina (K)" },
    { key: "PYG", label: "Paraguay Guarani (₲)" },
    { key: "PEN", label: "Peru Sol (S/.)" },
    { key: "PHP", label: "Philippines Peso (₱)" },
    { key: "PLN", label: "Poland Zloty (zł)" },
    { key: "QAR", label: "Qatar Riyal (QR)" },
    { key: "RON", label: "Romania Leu (RON)" },
    { key: "RUB", label: "Russia Ruble (руб.)" },
    { key: "RWF", label: "Rwanda Franc (FRw)" },
    { key: "SHP", label: "Saint Helena Pound (£)" },
    { key: "WST", label: "Samoa Tala (WS$)" },
    { key: "SAR", label: "Saudi Arabia Riyal (SR)" },
    { key: "SPL", label: "Seborga Luigino (-)" },
    { key: "RSD", label: "Serbia Dinar (d./д.)" },
    { key: "SCR", label: "Seychelles Rupee (SR)" },
    { key: "SLL", label: "Sierra Leone Leone (Le)" },
    { key: "SGD", label: "Singapore Dollar (S$)" },
    { key: "SBD", label: "Solomon Islands Dollar (SI$)" },
    { key: "SOS", label: "Somalia Shilling (Sh.So.)" },
    { key: "ZAR", label: "South Africa Rand (R)" },
    { key: "LKR", label: "Sri Lanka Rupee (Rs)" },
    { key: "SDG", label: "Sudan Pound (SDG)" },
    { key: "SRD", label: "Suriname Dollar ($)" },
    { key: "SZL", label: "Swaziland Lilangeni (L)" },
    { key: "SEK", label: "Sweden Krona (kr)" },
    { key: "CHF", label: "Switzerland Franc (SFr.)" },
    { key: "SYP", label: "Syria Pound (£S)" },
    { key: "STD", label: "São Tomé and Príncipe Dobra (Db)" },
    { key: "TWD", label: "Taiwan New Dollar (NT$)" },
    { key: "TJS", label: "Tajikistan Somoni (-)" },
    { key: "TZS", label: "Tanzania Shilling (TSh)" },
    { key: "THB", label: "Thailand Baht (฿)" },
    { key: "TOP", label: "Tonga Pa'anga (T$)" },
    { key: "TTD", label: "Trinidad and Tobago Dollar (TT$)" },
    { key: "TND", label: "Tunisia Dinar (DT)" },
    { key: "TRY", label: "Turkey Lira (₺)" },
    { key: "TMT", label: "Turkmenistan Manat (T)" },
    { key: "TVD", label: "Tuvalu Dollar (TV$)" },
    { key: "UGX", label: "Uganda Shilling (USh)" },
    { key: "UAH", label: "Ukraine Hryvnia (₴)" },
    { key: "AED", label: "United Arab Emirates Dirham (DH)" },
    { key: "GBP", label: "United Kingdom Pound (£)" },
    { key: "USD", label: "United States Dollar ($)" },
    { key: "UYU", label: "Uruguay Peso ($U)" },
    { key: "UZS", label: "Uzbekistan Som (U.S.)" },
    { key: "VUV", label: "Vanuatu Vatu (VT)" },
    { key: "VEF", label: "Venezuela Bolívar (Bs.)" },
    { key: "VND", label: "Viet Nam Dong (₫)" },
    { key: "YER", label: "Yemen Rial (Rl)" },
    { key: "ZMW", label: "Zambia Kwacha (K)" },
    { key: "ZMD", label: "Zimbabwe Dollar (ZM$)" },
  ]